import type { AppProps } from 'next/app';
import '../styles/main.scss';
import Layout from '@/components/layout/Layout';
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';
import { useEffect, useState } from 'react';
import Head from 'next/head';
import { Provider } from 'react-redux';
import store from '@/srore/store';
import LoaderInProgress from '@/components/progress-line/ProgressLine';

export default function App({ Component, pageProps }: AppProps) {
  const [isDark, setIsDark] = useState<boolean>(false);
  useEffect(() => {
    const darkThemeMq = window.matchMedia('(prefers-color-scheme: dark)');
    setIsDark(darkThemeMq.matches);
  }, []);

  return (
    <>
      <Head>
        <title>Painters-Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <div className={isDark ? 'theme-dark' : 'theme'}>
          <Header isDark={isDark} setIsDark={setIsDark} />
          <Layout>
            <LoaderInProgress />
            <Component {...pageProps} />
          </Layout>
          <Footer />
        </div>
      </Provider>
    </>
  );
}
