import '../styles/globals.scss';
import { useEffect, useState } from 'react';
import type { AppProps } from 'next/app';
import Footer from '@/components/footer/Footer';
import Head from 'next/head';
import Header from '@/components/header/Header';
import Layout from '@/components/layout/Layout';
import LoaderInProgress from '@/components/progress-line/ProgressLine';
import { Provider } from 'react-redux';
import store from '@/srore/store';

export default function App({ Component, pageProps }: AppProps) {
  const [isDark, setIsDark] = useState<boolean>(false);

  useEffect(() => {
    const darkThemeMq = window.matchMedia('(prefers-color-scheme: dark)');

    setIsDark(darkThemeMq.matches);
  }, []);

  return (
    <>
      <Head>
        <title>Painters-Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <div className={isDark ? 'theme-dark' : 'theme'}>
          <Header isDark={isDark} setIsDark={setIsDark} />
          <Layout isDark={isDark} >
            <LoaderInProgress />
            <Component isDark={isDark} {...pageProps} />
          </Layout>
          <Footer />
        </div>
      </Provider>
    </>
  );
}
